name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Angular application
        run: npm run build

      - name: Deploy to gh-pages branch
        uses: JamesIolom/gha-deploy-dist@master
        with:
          branch: gh-pages # Use gh-pages branch for hosting
          path: dist/dmfl  # Replace with your build output path
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}